### ISSUE TITLE
ImportError: No module named httplib2

### ISSUE THREAD

**Issue by isaacadam** [Amagnum/google-drive-to-youtube-video#1]
Error in the last cell in Google Colab Notebook:

`Traceback (most recent call last):
  File "upload_video.py", line 4, in <module>
    import httplib2
ImportError: No module named httplib2`

**Comment by Amagnum** [comment]
If there are multiple Python instances (2 & 3), try different pip, for example:

Python 2:
`pip2 install httplib2 --upgrade`

Python 3:
`pip3 install httplib2 --upgrade`

Make sure you use python 2
